apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: MyApp
  replicas: 2 
  template: 
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: myapp
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: myservice
spec:
  selector:
    app: MyApp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer